name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Software Component Analysis (SCA)
      run: npm audit --audit-level=high
    
    # Initialize CodeQL scanning
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript'

    # Autobuild attempts to build any compiled languages  
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    # Perform the CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Build application
      run: npm run build

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag richardjoseph1/modelmanager-frontend-kube-openwebui:latest

    - name: Push image to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker login -u richardjoseph1 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push richardjoseph1/modelmanager-frontend-kube-openwebui:latest