# This is the name of the consolidated workflow.
name: CI & CD Pipeline

# Triggers the workflow on push or pull request events but only for the "main" branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Lints the code and verifies the application builds successfully.
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm' # Enables caching for faster dependency installation

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build application
      run: npm run build

  # JOB 2: Runs security scans for vulnerable dependencies (SCA) and secrets.
  security-scans:
    name: Security Scans (SCA & Secrets)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Software Component Analysis (SCA)
      run: npm audit --audit-level=high

    - name: Static Application Security Testing (SAST) with Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml

  # JOB 3: Performs in-depth static analysis with CodeQL.
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript # Specific language for analysis

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript-typescript"

  # JOB 4: Builds and pushes the Docker image to Docker Hub.
  # This job will ONLY run after the three CI jobs above succeed, and only on a push to main.
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    # Define dependencies: This job waits for the CI jobs to be successful.
    needs: [lint-and-build, security-scans, codeql-analysis]
    
    # Define condition: This job only runs for push events on the main branch.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: richardjoseph1
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: richardjoseph1/modelmanager-frontend-kube-openwebui:latest